name: BBSToper
main: moe.feo.bbstoper.BBSToper
version: 3.6.8
authors: 
  - Fengshuai(R_Josef)
  - DreamVoid
website: https://www.mcbbs.net/thread-789082-1-1.html
softdepend:
  - PlaceholderAPI
commands:
  bbstoper:
    description: 'BBSToper 主命令'
    aliases: 
      - bt
      - poster
      - toper
    permission: bbstoper.user
    usage: For help, type /bbstoper help
permissions:
  bbstoper.admin:
    description: "BBSToper 管理员权限"
    default: op
    children:
      bbstoper.command.*: true
  bbstoper.user:
    description: "BBSToper 用户权限"
    default: true
    children:
      bbstoper.command.binding: true
      bbstoper.command.reward: true

  bbstoper.command.*:
    descriprion: 允许使用所有 /bbstoper 子命令
    default: op
    children:
      bbstoper.command.reload: true
      bbstoper.command.reward: true
      bbstoper.command.testreward: true
      bbstoper.command.binding: true
      bbstoper.command.list: true
      bbstoper.command.top: true
      bbstoper.command.check: true
      bbstoper.command.delete: true
  bbstoper.command.reload:
    description: 允许使用 /bbstoper reload
    default: op
  bbstoper.command.reward:
    description: 允许使用 /bbstoper reward
    default: op
  bbstoper.command.testreward:
    description: 允许使用 /bbstoper testreward
    default: op
  bbstoper.command.binding:
    description: 允许使用 /bbstoper binding
    default: op
  bbstoper.command.list:
    description: 允许使用 /bbstoper list
    default: op
  bbstoper.command.top:
    description: 允许使用 /bbstoper top
    default: op
  bbstoper.command.check:
    description: 允许使用 /bbstoper check
    default: op
  bbstoper.command.delete:
    description: 允许使用 /bbstoper delete
    default: op

  bbstoper.bypass.querycooldown:
    description: 允许跳过顶帖间隔
    default: false